= Assignment for Rabobank Java Dev/Ops role
:secnums:
:sectnumlevels: 2
:toc: left

This project is an exercise spilt into 3 essential parts:

* Dockerized WireMock standalone service to serve user data in Json format (mock an external service).
  The user must be searchable by first and/or surname. The Wiremock stubs are user data populated from random
  data found at https://randomuser.me
* A SpringBoot application that can query the external service for user data and make it available to be displayed
  in an HTML page.
* An HTML page that displays user data from the external service. Search functionality required for first and surname.
  User first name, surname, date of birth (dd-MM-yyyy), gender, and picture are to be displayed.

== Prerequisites

To be able to start all aspects of this project you need:

 - https://www.oracle.com/java/technologies/javase-downloads.html[Java Development Kit 8 and 11^]
 - http://maven.apache.org/download.cgi[Maven 3.6^]
 - Docker 19 + docker-compose
 - Install the Lombok plugin for Intellij

== Quickstart

 1. Clone this repository
 2. Run `docker build -t user-mock:local ./wiremock/stubs/`
 3. Run `docker-compose up -d` to start required dependencies.
 4. Run `mvn compile` to build project.
 5. Run `nl.isaza.rabo.assignment.AssignmentApplication` to spin up the application.

== Resource

 - The application runs on http://localhost:8080
 - The WireMock (Docker container) can be accessed on http://localhost:8000.
   To test it is running: `curl "http://localhost:8000/users?first=Hugo&surname=Lucas"`

== Project Status
This project is incomplete.

#DONE#

 - Docker service configuration with Wiremock standalone service to service user data.
   Searchable by first and/or surname.
 - Spring Application: preliminary User model,
   User Dto, and REST controller, UserService class (function signatures), UserControllerTest.
 - Readme documentation.

#TODO#

 - Client to pull json data from external service (if in reality the user data could come from
   other sources in future then I would probably follow some sort of Factory pattern).
 - Map json data to model (most likely using the Jackson ObjectMapper)
 - Wire it to UserService class
 - Unit tests for service and controller methods etc. covering all reasonable edge cases
 - Error mappings for api
 - Determine if nulls are allowed, and how to handle
 - Swagger docs for application api
 - Check code coverage etc. in some tool like SonarCloud
 - Check Javadoc comments in classes are sufficient
 - Implement front end to search and display user data
 - Front end tests for functionality.








